version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - AUTH_SECRET=${AUTH_SECRET}
      - AUTH_TRUST_HOST=True
      - ALIBABA_API_KEY=${ALIBABA_API_KEY}
      - KIMI_API_KEY=${KIMI_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_BASE_URL=${OPENAI_BASE_URL}
    depends_on:
      - db

  db:
    image: ankane/pgvector
    environment:
      POSTGRES_DB: api
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: ChangeMe
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata: